### ISSUE TITLE
libyui-ncurses fails to build in YaST:Head

### ISSUE THREAD

**Issue by gabi2** [libyui/libyui-old#55]
It seems that "fix build with graphiz >= 2.30.0" which includes &lt;graphviz/types.h&gt; causes build failure of libyui-ncurses:

Scanning dependencies of target yui-ncurses
[  1%] Building CXX object src/CMakeFiles/yui-ncurses.dir/position.cc.o
[  3%] Building CXX object src/CMakeFiles/yui-ncurses.dir/YNCursesUI.cc.o
In file included from /usr/include/graphviz/types.h:32:0,
                 from /usr/include/yui/YGraph.h:44,
                 from /usr/include/yui/YOptionalWidgetFactory.h:34,
                 from /development/libyui/libyui-ncurses/src/NCOptionalWidgetFactory.h:29,
                 from /development/libyui/libyui-ncurses/src/YNCursesUI.cc:43:
/usr/include/graphviz/geom.h:35:34: error: ‘typedef struct box box’ redeclared as different kind of symbol
In file included from /development/libyui/libyui-ncurses/src/NCurses.h:37:0,
                 from /development/libyui/libyui-ncurses/src/YNCursesUI.h:33,
                 from /development/libyui/libyui-ncurses/src/YNCursesUI.cc:25:
/usr/include/ncurses6/ncursesw/curses.h:584:28: error: previous declaration of ‘int box(WINDOW_, chtype, chtype)’
make[2]: *_\* [src/CMakeFiles/yui-ncurses.dir/YNCursesUI.cc.o] Fehler 1
make[1]: **\* [src/CMakeFiles/yui-ncurses.dir/all] Fehler 2
make: **\* [all] Fehler 2
